/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model3({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/clg2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 19, 0]} scale={[22, 15, 13]}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["building maiin"]}
        />
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={nodes.Cube001_1.material}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={nodes.Cube001_2.material}
        />
        <mesh
          geometry={nodes.Cube001_3.geometry}
          material={nodes.Cube001_3.material}
        />
        <mesh
          geometry={nodes.Cube001_4.geometry}
          material={nodes.Cube001_4.material}
        />
        <mesh
          geometry={nodes.Cube001_5.geometry}
          material={nodes.Cube001_5.material}
        />
        <mesh
          geometry={nodes.Cube001_6.geometry}
          material={materials.Plastic}
        />
        <mesh
          geometry={nodes.Cube001_7.geometry}
          material={nodes.Cube001_7.material}
        />
        <mesh
          geometry={nodes.Cube001_8.geometry}
          material={nodes.Cube001_8.material}
        />
      </group>
      <mesh
        geometry={nodes.ground.geometry}
        material={materials.dirtish}
        position={[0, -1.65, 0]}
        scale={[37.5, 3.56, 37.5]}
      />
    </group>
  );
}

useGLTF.preload("/clg2.glb");
