/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model4({ zoomToView }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/clg3.glb");
  return (
    <group
      ref={group}
      dispose={null}
      onClick={(e) => zoomToView(e.object.position)}
    >
      <group position={[0, 19, 0]} scale={[22, 15, 13]}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["building maiin"]}
        />
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={nodes.Cube001_1.material}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={nodes.Cube001_2.material}
        />
        <mesh
          geometry={nodes.Cube001_3.geometry}
          material={nodes.Cube001_3.material}
        />
        <mesh
          geometry={nodes.Cube001_4.geometry}
          material={nodes.Cube001_4.material}
        />
        <mesh
          geometry={nodes.Cube001_5.geometry}
          material={nodes.Cube001_5.material}
        />
        <mesh
          geometry={nodes.Cube001_6.geometry}
          material={materials.Plastic}
        />
        <mesh
          geometry={nodes.Cube001_7.geometry}
          material={nodes.Cube001_7.material}
        />
        <mesh
          geometry={nodes.Cube001_8.geometry}
          material={nodes.Cube001_8.material}
        />
      </group>
      <group position={[0, -1.65, 0]} scale={[37.5, 3.56, 37.5]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.dirtish} />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={nodes.Plane_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[2.72, 0, -59.64]}
        scale={[95.17, 8.37, 8.37]}
      />
    </group>
  );
}

useGLTF.preload("/clg3.glb");
