/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model5({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/clg4.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 19, 0]} scale={[22, 15, 13]}>
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={nodes.Cube001_1.material}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={nodes.Cube001_2.material}
        />
        <mesh
          geometry={nodes.Cube001_3.geometry}
          material={nodes.Cube001_3.material}
        />
        <mesh
          geometry={nodes.Cube001_4.geometry}
          material={nodes.Cube001_4.material}
        />
        <mesh
          geometry={nodes.Cube001_5.geometry}
          material={nodes.Cube001_5.material}
        />
        <mesh
          geometry={nodes.Cube001_6.geometry}
          material={nodes.Cube001_6.material}
        />
        <mesh
          geometry={nodes.Cube001_7.geometry}
          material={materials.Plastic}
        />
        <mesh
          geometry={nodes.Cube001_8.geometry}
          material={nodes.Cube001_8.material}
        />
        <mesh
          geometry={nodes.Cube001_9.geometry}
          material={nodes.Cube001_9.material}
        />
      </group>
      <group position={[0, -1.65, 0]} scale={[50.55, 3.56, 37.5]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.dirtish} />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={nodes.Plane_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[2.72, 0, -59.64]}
        scale={[95.17, 8.37, 8.37]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[55.02, 15.98, -2.25]}
        scale={[19.97, 17.31, 17.31]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-50.31, 15.98, -2.25]}
        scale={[19.97, 17.31, 17.31]}
      />
    </group>
  );
}

useGLTF.preload("/clg4.glb");
