/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/compressed_clg.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[304.74, 0, -178.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.66, 3, 3.04]}>
        <group position={[-0.17, -0.11, -2.95]} scale={[37.64, 30.5, 2.14]}>
          <mesh geometry={nodes.Cube_0.geometry} material={materials.Ground} />
        </group>
        <group position={[0.33, -0.11, 5.59]} scale={3.24}>
          <mesh geometry={nodes.Cube001_0.geometry} material={nodes.Cube001_0.material} />
        </group>
        <group position={[-12.78, -17.11, 0.65]} scale={0.45}>
          <mesh geometry={nodes.Cube003_0.geometry} material={nodes.Cube003_0.material} />
        </group>
        <group position={[-7.07, -17.52, 0.53]} rotation={[0, 0, -3.04]} scale={[-3.01, -0.67, -0.33]}>
          <mesh geometry={nodes.Cube004_0.geometry} material={nodes.Cube004_0.material} />
        </group>
        <group position={[8.06, -18.49, 0.78]} scale={-0.56}>
          <mesh geometry={nodes.Cube005_0.geometry} material={nodes.Cube005_0.material} />
        </group>
        <group position={[-2.38, -18.01, 1.06]} rotation={[0.02, 0.19, 2.64]} scale={[-3.01, -0.67, -0.33]}>
          <mesh geometry={nodes.Cube006_0.geometry} material={nodes.Cube006_0.material} />
        </group>
        <group position={[5.89, -17.11, 0.53]} scale={0.33}>
          <mesh geometry={nodes.Cube007_0.geometry} material={nodes.Cube007_0.material} />
        </group>
        <group position={[11.5, 13.69, 2.1]} rotation={[-0.07, 0.11, 2.46]} scale={[-3.01, -0.67, -0.33]}>
          <mesh geometry={nodes.Cube008_0.geometry} material={nodes.Cube008_0.material} />
        </group>
        <group position={[12.18, 15.52, 1.56]} rotation={[0, 0, -0.25]} scale={[3.84, 1.17, 0.26]}>
          <mesh geometry={nodes.Cube009_0.geometry} material={nodes.Cube009_0.material} />
        </group>
        <group position={[-4.21, 19.18, 6.28]} rotation={[-0.22, -0.07, 2.45]} scale={[-3.01, -0.67, -0.33]}>
          <mesh geometry={nodes.Cube010_0.geometry} material={nodes.Cube010_0.material} />
        </group>
        <group position={[7.92, 16.06, 1.53]} scale={0.22}>
          <mesh geometry={nodes.Cube011_0.geometry} material={nodes.Cube011_0.material} />
        </group>
        <group position={[-17.5, 7.26, 1.96]} rotation={[-0.03, -0.14, 0.65]} scale={[3.84, 1.17, 0.26]}>
          <mesh geometry={nodes.Cube012_0.geometry} material={nodes.Cube012_0.material} />
        </group>
        <group position={[1.42, -15.94, 0.45]} rotation={[0, 0, -0.25]} scale={[3.84, 1.17, 0.26]}>
          <mesh geometry={nodes.Cube013_0.geometry} material={nodes.Cube013_0.material} />
        </group>
        <group position={[-19.27, 2.75, 1.7]} rotation={[0, 0, -2.56]} scale={[0.25, 0.25, 0.25]}>
          <mesh geometry={nodes.Cube014_0.geometry} material={nodes.Cube014_0.material} />
        </group>
        <group position={[21.02, -21.93, 4.41]} scale={[0.76, 0.76, 5.21]}>
          <mesh geometry={nodes.Cube015_0.geometry} material={nodes.Cube015_0.material} />
        </group>
        <group position={[-19.98, -21.93, 4.41]} scale={[0.76, 0.76, 5.21]}>
          <mesh geometry={nodes.Cube016_0.geometry} material={nodes.Cube016_0.material} />
        </group>
        <group position={[-19.98, 21.61, 4.41]} scale={[0.76, 0.76, 5.21]}>
          <mesh geometry={nodes.Cube017_0.geometry} material={nodes.Cube017_0.material} />
        </group>
        <group position={[21.02, 21.61, 4.41]} scale={[0.76, 0.76, 5.21]}>
          <mesh geometry={nodes.Cube018_0.geometry} material={nodes.Cube018_0.material} />
        </group>
        <group position={[-13.99, 3.52, 1.52]} rotation={[0.21, 0.25, 2.25]} scale={[-3.01, -0.67, -0.33]}>
          <mesh geometry={nodes.Cube019_0.geometry} material={nodes.Cube019_0.material} />
        </group>
        <group position={[-25.15, 18.37, 0.39]} rotation={[-Math.PI, 0, -2.6]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube054_0.geometry} material={nodes.Cube054_0.material} />
          <mesh geometry={nodes.Cube054_1.geometry} material={nodes.Cube054_1.material} />
        </group>
        <group position={[-28.98, 12.41, -0.03]} rotation={[-Math.PI, 0, -3.05]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube058_0.geometry} material={nodes.Cube058_0.material} />
          <mesh geometry={nodes.Cube058_1.geometry} material={nodes.Cube058_1.material} />
        </group>
        <group position={[-30.4, 5.44, 0.39]} rotation={[-Math.PI, 0, -2.6]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube065_0.geometry} material={nodes.Cube065_0.material} />
          <mesh geometry={nodes.Cube065_1.geometry} material={nodes.Cube065_1.material} />
        </group>
        <group position={[-30.76, -1.67, -0.03]} rotation={[-Math.PI, 0, -3.05]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube066_0.geometry} material={nodes.Cube066_0.material} />
          <mesh geometry={nodes.Cube066_1.geometry} material={nodes.Cube066_1.material} />
        </group>
        <group position={[-29.19, -8.44, 0.39]} rotation={[-Math.PI, 0, -2.6]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube067_0.geometry} material={nodes.Cube067_0.material} />
          <mesh geometry={nodes.Cube067_1.geometry} material={nodes.Cube067_1.material} />
        </group>
        <group position={[-25.86, -15.24, -0.03]} rotation={[-Math.PI, 0, -3.05]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube068_0.geometry} material={nodes.Cube068_0.material} />
          <mesh geometry={nodes.Cube068_1.geometry} material={nodes.Cube068_1.material} />
        </group>
        <group position={[24.61, 18.55, -0.03]} rotation={[-Math.PI, 0, 0]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube069_0.geometry} material={nodes.Cube069_0.material} />
          <mesh geometry={nodes.Cube069_1.geometry} material={nodes.Cube069_1.material} />
        </group>
        <group position={[28.57, 12.09, 0.39]} rotation={[Math.PI, 0, 0.44]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube070_0.geometry} material={nodes.Cube070_0.material} />
          <mesh geometry={nodes.Cube070_1.geometry} material={nodes.Cube070_1.material} />
        </group>
        <group position={[30.77, 5.5, -0.03]} rotation={[-Math.PI, 0, 0]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube071_0.geometry} material={nodes.Cube071_0.material} />
          <mesh geometry={nodes.Cube071_1.geometry} material={nodes.Cube071_1.material} />
        </group>
        <group position={[31.08, -1.61, 0.39]} rotation={[Math.PI, 0, 0.44]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube072_0.geometry} material={nodes.Cube072_0.material} />
          <mesh geometry={nodes.Cube072_1.geometry} material={nodes.Cube072_1.material} />
        </group>
        <group position={[30.32, -8.69, -0.03]} rotation={[-Math.PI, 0, 0]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube073_0.geometry} material={nodes.Cube073_0.material} />
          <mesh geometry={nodes.Cube073_1.geometry} material={nodes.Cube073_1.material} />
        </group>
        <group position={[27.07, -14.98, 0.39]} rotation={[Math.PI, 0, 0.44]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube074_0.geometry} material={nodes.Cube074_0.material} />
          <mesh geometry={nodes.Cube074_1.geometry} material={nodes.Cube074_1.material} />
        </group>
        <group position={[17.17, 22.35, 0.39]} rotation={[-Math.PI, 0, -1.04]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube075_0.geometry} material={nodes.Cube075_0.material} />
          <mesh geometry={nodes.Cube075_1.geometry} material={nodes.Cube075_1.material} />
        </group>
        <group position={[11.2, 26.15, -0.03]} rotation={[-Math.PI, 0, -1.48]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube076_0.geometry} material={nodes.Cube076_0.material} />
          <mesh geometry={nodes.Cube076_1.geometry} material={nodes.Cube076_1.material} />
        </group>
        <group position={[4.21, 27.53, 0.39]} rotation={[-Math.PI, 0, -1.04]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube077_0.geometry} material={nodes.Cube077_0.material} />
          <mesh geometry={nodes.Cube077_1.geometry} material={nodes.Cube077_1.material} />
        </group>
        <group position={[-2.9, 27.85, -0.03]} rotation={[-Math.PI, 0, -1.48]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube078_0.geometry} material={nodes.Cube078_0.material} />
          <mesh geometry={nodes.Cube078_1.geometry} material={nodes.Cube078_1.material} />
        </group>
        <group position={[-9.66, 26.24, 0.39]} rotation={[-Math.PI, 0, -1.04]} scale={[-0.31, -0.3, -1.29]}>
          <mesh geometry={nodes.Cube079_0.geometry} material={nodes.Cube079_0.material} />
          <mesh geometry={nodes.Cube079_1.geometry} material={nodes.Cube079_1.material} />
        </group>
        <group position={[-16.44, 22.88, -0.03]} rotation={[-Math.PI, 0, -1.48]} scale={[-0.29, -0.28, -0.9]}>
          <mesh geometry={nodes.Cube080_0.geometry} material={nodes.Cube080_0.material} />
          <mesh geometry={nodes.Cube080_1.geometry} material={nodes.Cube080_1.material} />
        </group>
        <group position={[-2.61, -22.92, -0.85]} rotation={[0.06, -0.02, -0.25]} scale={[0.98, 0.66, 0.09]}>
          <mesh geometry={nodes.Icosphere002_0.geometry} material={nodes.Icosphere002_0.material} />
        </group>
        <group position={[-0.66, -23.35, -0.85]} rotation={[0.05, 0.03, 0.46]} scale={[0.98, 0.66, 0.09]}>
          <mesh geometry={nodes.Icosphere003_0.geometry} material={nodes.Icosphere003_0.material} />
        </group>
        <group position={[1, -22.87, -0.85]} rotation={[0.03, -0.05, -1]} scale={[0.98, 0.66, 0.09]}>
          <mesh geometry={nodes.Icosphere004_0.geometry} material={nodes.Icosphere004_0.material} />
        </group>
        <group position={[2.66, -22.87, -0.85]} rotation={[-0.04, -0.05, -2.28]} scale={[0.98, 0.66, 0.09]}>
          <mesh geometry={nodes.Icosphere005_0.geometry} material={nodes.Icosphere005_0.material} />
        </group>
        <group position={[2.66, -24.53, -0.85]} rotation={[0.06, -0.02, -0.4]} scale={[0.98, 0.66, 0.09]}>
          <mesh geometry={nodes.Icosphere006_0.geometry} material={nodes.Icosphere006_0.material} />
        </group>
        <group position={[1, -24.53, -0.85]} rotation={[-0.05, 0.03, 2.59]} scale={[0.98, 0.66, 0.09]}>
          <mesh geometry={nodes.Icosphere007_0.geometry} material={nodes.Icosphere007_0.material} />
        </group>
        <group position={[-0.66, -25.01, -0.85]} rotation={[0.05, -0.03, -0.6]} scale={[0.98, 0.66, 0.09]}>
          <mesh geometry={nodes.Icosphere008_0.geometry} material={nodes.Icosphere008_0.material} />
        </group>
        <group position={[-2.61, -24.57, -0.85]} rotation={[0.05, 0.03, 0.6]} scale={[0.98, 0.66, 0.09]}>
          <mesh geometry={nodes.Icosphere009_0.geometry} material={nodes.Icosphere009_0.material} />
        </group>
        <group position={[-2.61, -26.33, -0.85]} rotation={[-3.09, -0.03, 2.55]} scale={[-0.98, -0.66, -0.09]}>
          <mesh geometry={nodes.Icosphere010_0.geometry} material={nodes.Icosphere010_0.material} />
        </group>
        <group position={[-0.66, -26.49, -0.85]} rotation={[3.08, -0.02, 0.3]} scale={[-0.98, -0.66, -0.09]}>
          <mesh geometry={nodes.Icosphere011_0.geometry} material={nodes.Icosphere011_0.material} />
        </group>
        <group position={[1, -26.31, -0.85]} rotation={[-3.12, -0.06, 1.88]} scale={[-0.98, -0.66, -0.09]}>
          <mesh geometry={nodes.Icosphere012_0.geometry} material={nodes.Icosphere012_0.material} />
        </group>
        <group position={[2.66, -26.29, -0.85]} rotation={[3.11, -0.05, 1.1]} scale={[-0.98, -0.66, -0.09]}>
          <mesh geometry={nodes.Icosphere013_0.geometry} material={nodes.Icosphere013_0.material} />
        </group>
        <group position={[2.66, -28.08, -0.85]} rotation={[3.09, -0.03, -2.68]} scale={[-0.98, -0.66, -0.09]}>
          <mesh geometry={nodes.Icosphere014_0.geometry} material={nodes.Icosphere014_0.material} />
        </group>
        <group position={[0.93, -28.15, -0.85]} rotation={[-3.11, 0.05, 1]} scale={[-0.98, -0.66, -0.09]}>
          <mesh geometry={nodes.Icosphere015_0.geometry} material={nodes.Icosphere015_0.material} />
        </group>
        <group position={[-0.66, -28.15, -0.85]} rotation={[-3.09, -0.03, 2.68]} scale={[-0.98, -0.66, -0.09]}>
          <mesh geometry={nodes.Icosphere016_0.geometry} material={nodes.Icosphere016_0.material} />
        </group>
        <group position={[-2.61, -28.15, -0.85]} rotation={[-3.08, 0.02, -2.89]} scale={[-0.98, -0.66, -0.09]}>
          <mesh geometry={nodes.Icosphere017_0.geometry} material={nodes.Icosphere017_0.material} />
        </group>
        <group position={[-11.12, -24.02, -0.85]} rotation={[0.06, -0.02, -0.25]} scale={[-7.68, -6.59, -0.72]}>
          <mesh geometry={nodes.Icosphere018_0.geometry} material={nodes.Icosphere018_0.material} />
        </group>
        <group position={[10.77, -23.42, -1.14]} rotation={[-0.05, 0.04, 2.52]} scale={[-7.68, -6.59, -0.72]}>
          <mesh geometry={nodes.Icosphere019_0.geometry} material={nodes.Icosphere019_0.material} />
        </group>
      </group>
      <group position={[301.54, -3.07, 114.61]} rotation={[-Math.PI / 2, 0, -2.01]} scale={0.24}>
        <group position={[0, 0, 7.87]}>
          <group position={[18.42, 11.59, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2_1.geometry} material={nodes.Material2_1.material} />
            <mesh geometry={nodes.Material2_2.geometry} material={nodes.Material2_2.material} />
          </group>
          <group position={[68.04, 34.65, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2002_1.geometry} material={nodes.Material2002_1.material} />
            <mesh geometry={nodes.Material2002_2.geometry} material={nodes.Material2002_2.material} />
          </group>
          <group position={[117.66, 57.72, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2003_1.geometry} material={nodes.Material2003_1.material} />
            <mesh geometry={nodes.Material2003_2.geometry} material={nodes.Material2003_2.material} />
          </group>
          <group position={[167.28, 80.78, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2004_1.geometry} material={nodes.Material2004_1.material} />
            <mesh geometry={nodes.Material2004_2.geometry} material={nodes.Material2004_2.material} />
          </group>
          <group position={[216.89, 103.85, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2005_1.geometry} material={nodes.Material2005_1.material} />
            <mesh geometry={nodes.Material2005_2.geometry} material={nodes.Material2005_2.material} />
          </group>
          <group position={[175.9, 192.04, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2006_1.geometry} material={nodes.Material2006_1.material} />
            <mesh geometry={nodes.Material2006_2.geometry} material={nodes.Material2006_2.material} />
          </group>
          <group position={[126.23, 168.95, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2007_1.geometry} material={nodes.Material2007_1.material} />
            <mesh geometry={nodes.Material2007_2.geometry} material={nodes.Material2007_2.material} />
          </group>
          <group position={[76.56, 145.86, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2008_1.geometry} material={nodes.Material2008_1.material} />
            <mesh geometry={nodes.Material2008_2.geometry} material={nodes.Material2008_2.material} />
          </group>
          <group position={[26.89, 122.77, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2009_1.geometry} material={nodes.Material2009_1.material} />
            <mesh geometry={nodes.Material2009_2.geometry} material={nodes.Material2009_2.material} />
          </group>
          <group position={[-22.78, 99.68, 8.72]} scale={[1, 0.72, 1]}>
            <mesh geometry={nodes.Material2010.geometry} material={nodes.Material2010.material} />
            <mesh geometry={nodes.Material2010_1.geometry} material={nodes.Material2010_1.material} />
          </group>
          <mesh geometry={nodes.Material3.geometry} material={materials.material} position={[17.94, 14.93, 11]} />
        </group>
      </group>
      <group position={[304.58, 3.68, 116.85]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3_1.geometry} material={nodes.Mesh_3_1.material} />
        <mesh geometry={nodes.Mesh_3_2.geometry} material={nodes.Mesh_3_2.material} />
        <mesh geometry={nodes.Mesh_3_3.geometry} material={nodes.Mesh_3_3.material} />
        <mesh geometry={nodes.Mesh_3_4.geometry} material={nodes.Mesh_3_4.material} />
        <mesh geometry={nodes.Mesh_3_5.geometry} material={nodes.Mesh_3_5.material} />
      </group>
      <group position={[302.65, 4.81, 118.58]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0_1'].geometry}
          material={nodes['Box001_02_-_Default_0_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0_2'].geometry}
          material={nodes['Box001_02_-_Default_0_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0_3'].geometry}
          material={nodes['Box001_02_-_Default_0_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0_4'].geometry}
          material={nodes['Box001_02_-_Default_0_4'].material}
        />
      </group>
      <group position={[300.23, 4.81, 122.29]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0001_1'].geometry}
          material={nodes['Box001_02_-_Default_0001_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0001_2'].geometry}
          material={nodes['Box001_02_-_Default_0001_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0001_3'].geometry}
          material={nodes['Box001_02_-_Default_0001_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0001_4'].geometry}
          material={nodes['Box001_02_-_Default_0001_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0'].geometry}
        material={nodes['Plane004_13_-_Default_0'].material}
        position={[303.34, 2.86, 121.64]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0.geometry}
        material={nodes.Plane001_Material002_0.material}
        position={[304.38, 2.79, 119.2]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[304.58, 3.68, 130.16]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3001_1.geometry} material={nodes.Mesh_3001_1.material} />
        <mesh geometry={nodes.Mesh_3001_2.geometry} material={nodes.Mesh_3001_2.material} />
        <mesh geometry={nodes.Mesh_3001_3.geometry} material={nodes.Mesh_3001_3.material} />
        <mesh geometry={nodes.Mesh_3001_4.geometry} material={nodes.Mesh_3001_4.material} />
        <mesh geometry={nodes.Mesh_3001_5.geometry} material={nodes.Mesh_3001_5.material} />
      </group>
      <group position={[302.65, 4.81, 131.88]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0002_1'].geometry}
          material={nodes['Box001_02_-_Default_0002_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0002_2'].geometry}
          material={nodes['Box001_02_-_Default_0002_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0002_3'].geometry}
          material={nodes['Box001_02_-_Default_0002_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0002_4'].geometry}
          material={nodes['Box001_02_-_Default_0002_4'].material}
        />
      </group>
      <group position={[300.23, 4.81, 135.59]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0003_1'].geometry}
          material={nodes['Box001_02_-_Default_0003_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0003_2'].geometry}
          material={nodes['Box001_02_-_Default_0003_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0003_3'].geometry}
          material={nodes['Box001_02_-_Default_0003_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0003_4'].geometry}
          material={nodes['Box001_02_-_Default_0003_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0001'].geometry}
        material={nodes['Plane004_13_-_Default_0001'].material}
        position={[303.34, 2.86, 134.95]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0001.geometry}
        material={nodes.Plane001_Material002_0001.material}
        position={[304.38, 2.79, 132.5]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[304.58, 3.68, 143.46]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3002_1.geometry} material={nodes.Mesh_3002_1.material} />
        <mesh geometry={nodes.Mesh_3002_2.geometry} material={nodes.Mesh_3002_2.material} />
        <mesh geometry={nodes.Mesh_3002_3.geometry} material={nodes.Mesh_3002_3.material} />
        <mesh geometry={nodes.Mesh_3002_4.geometry} material={nodes.Mesh_3002_4.material} />
        <mesh geometry={nodes.Mesh_3002_5.geometry} material={nodes.Mesh_3002_5.material} />
      </group>
      <group position={[302.65, 4.81, 145.18]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0004_1'].geometry}
          material={nodes['Box001_02_-_Default_0004_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0004_2'].geometry}
          material={nodes['Box001_02_-_Default_0004_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0004_3'].geometry}
          material={nodes['Box001_02_-_Default_0004_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0004_4'].geometry}
          material={nodes['Box001_02_-_Default_0004_4'].material}
        />
      </group>
      <group position={[300.23, 4.81, 148.89]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0005_1'].geometry}
          material={nodes['Box001_02_-_Default_0005_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0005_2'].geometry}
          material={nodes['Box001_02_-_Default_0005_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0005_3'].geometry}
          material={nodes['Box001_02_-_Default_0005_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0005_4'].geometry}
          material={nodes['Box001_02_-_Default_0005_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0002'].geometry}
        material={nodes['Plane004_13_-_Default_0002'].material}
        position={[303.34, 2.86, 148.25]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0002.geometry}
        material={nodes.Plane001_Material002_0002.material}
        position={[304.38, 2.79, 145.81]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[304.58, 3.68, 156.76]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3003_1.geometry} material={nodes.Mesh_3003_1.material} />
        <mesh geometry={nodes.Mesh_3003_2.geometry} material={nodes.Mesh_3003_2.material} />
        <mesh geometry={nodes.Mesh_3003_3.geometry} material={nodes.Mesh_3003_3.material} />
        <mesh geometry={nodes.Mesh_3003_4.geometry} material={nodes.Mesh_3003_4.material} />
        <mesh geometry={nodes.Mesh_3003_5.geometry} material={nodes.Mesh_3003_5.material} />
      </group>
      <group position={[302.65, 4.81, 158.49]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0006_1'].geometry}
          material={nodes['Box001_02_-_Default_0006_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0006_2'].geometry}
          material={nodes['Box001_02_-_Default_0006_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0006_3'].geometry}
          material={nodes['Box001_02_-_Default_0006_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0006_4'].geometry}
          material={nodes['Box001_02_-_Default_0006_4'].material}
        />
      </group>
      <group position={[300.23, 4.81, 162.2]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0007_1'].geometry}
          material={nodes['Box001_02_-_Default_0007_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0007_2'].geometry}
          material={nodes['Box001_02_-_Default_0007_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0007_3'].geometry}
          material={nodes['Box001_02_-_Default_0007_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0007_4'].geometry}
          material={nodes['Box001_02_-_Default_0007_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0003'].geometry}
        material={nodes['Plane004_13_-_Default_0003'].material}
        position={[303.34, 2.86, 161.55]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0003.geometry}
        material={nodes.Plane001_Material002_0003.material}
        position={[304.38, 2.79, 159.11]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[304.58, 3.68, 170.07]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3004_1.geometry} material={nodes.Mesh_3004_1.material} />
        <mesh geometry={nodes.Mesh_3004_2.geometry} material={nodes.Mesh_3004_2.material} />
        <mesh geometry={nodes.Mesh_3004_3.geometry} material={nodes.Mesh_3004_3.material} />
        <mesh geometry={nodes.Mesh_3004_4.geometry} material={nodes.Mesh_3004_4.material} />
        <mesh geometry={nodes.Mesh_3004_5.geometry} material={nodes.Mesh_3004_5.material} />
      </group>
      <group position={[302.65, 4.81, 171.79]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0008_1'].geometry}
          material={nodes['Box001_02_-_Default_0008_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0008_2'].geometry}
          material={nodes['Box001_02_-_Default_0008_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0008_3'].geometry}
          material={nodes['Box001_02_-_Default_0008_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0008_4'].geometry}
          material={nodes['Box001_02_-_Default_0008_4'].material}
        />
      </group>
      <group position={[300.23, 4.81, 175.5]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0009_1'].geometry}
          material={nodes['Box001_02_-_Default_0009_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0009_2'].geometry}
          material={nodes['Box001_02_-_Default_0009_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0009_3'].geometry}
          material={nodes['Box001_02_-_Default_0009_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0009_4'].geometry}
          material={nodes['Box001_02_-_Default_0009_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0004'].geometry}
        material={nodes['Plane004_13_-_Default_0004'].material}
        position={[303.34, 2.86, 174.85]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0004.geometry}
        material={nodes.Plane001_Material002_0004.material}
        position={[304.38, 2.79, 172.41]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[328.22, 3.68, 170.07]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3005_1.geometry} material={nodes.Mesh_3005_1.material} />
        <mesh geometry={nodes.Mesh_3005_2.geometry} material={nodes.Mesh_3005_2.material} />
        <mesh geometry={nodes.Mesh_3005_3.geometry} material={nodes.Mesh_3005_3.material} />
        <mesh geometry={nodes.Mesh_3005_4.geometry} material={nodes.Mesh_3005_4.material} />
        <mesh geometry={nodes.Mesh_3005_5.geometry} material={nodes.Mesh_3005_5.material} />
      </group>
      <group position={[326.3, 4.81, 171.79]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0010_1'].geometry}
          material={nodes['Box001_02_-_Default_0010_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0010_2'].geometry}
          material={nodes['Box001_02_-_Default_0010_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0010_3'].geometry}
          material={nodes['Box001_02_-_Default_0010_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0010_4'].geometry}
          material={nodes['Box001_02_-_Default_0010_4'].material}
        />
      </group>
      <group position={[323.87, 4.81, 175.5]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0011_1'].geometry}
          material={nodes['Box001_02_-_Default_0011_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0011_2'].geometry}
          material={nodes['Box001_02_-_Default_0011_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0011_3'].geometry}
          material={nodes['Box001_02_-_Default_0011_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0011_4'].geometry}
          material={nodes['Box001_02_-_Default_0011_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0005'].geometry}
        material={nodes['Plane004_13_-_Default_0005'].material}
        position={[326.99, 2.86, 174.85]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0005.geometry}
        material={nodes.Plane001_Material002_0005.material}
        position={[328.02, 2.79, 172.41]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[328.22, 3.68, 156.75]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3006_1.geometry} material={nodes.Mesh_3006_1.material} />
        <mesh geometry={nodes.Mesh_3006_2.geometry} material={nodes.Mesh_3006_2.material} />
        <mesh geometry={nodes.Mesh_3006_3.geometry} material={nodes.Mesh_3006_3.material} />
        <mesh geometry={nodes.Mesh_3006_4.geometry} material={nodes.Mesh_3006_4.material} />
        <mesh geometry={nodes.Mesh_3006_5.geometry} material={nodes.Mesh_3006_5.material} />
      </group>
      <group position={[326.3, 4.81, 158.47]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0012_1'].geometry}
          material={nodes['Box001_02_-_Default_0012_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0012_2'].geometry}
          material={nodes['Box001_02_-_Default_0012_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0012_3'].geometry}
          material={nodes['Box001_02_-_Default_0012_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0012_4'].geometry}
          material={nodes['Box001_02_-_Default_0012_4'].material}
        />
      </group>
      <group position={[323.87, 4.81, 162.18]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0013_1'].geometry}
          material={nodes['Box001_02_-_Default_0013_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0013_2'].geometry}
          material={nodes['Box001_02_-_Default_0013_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0013_3'].geometry}
          material={nodes['Box001_02_-_Default_0013_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0013_4'].geometry}
          material={nodes['Box001_02_-_Default_0013_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0006'].geometry}
        material={nodes['Plane004_13_-_Default_0006'].material}
        position={[326.99, 2.86, 161.54]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0006.geometry}
        material={nodes.Plane001_Material002_0006.material}
        position={[328.02, 2.79, 159.1]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[328.22, 3.68, 143.43]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3007_1.geometry} material={nodes.Mesh_3007_1.material} />
        <mesh geometry={nodes.Mesh_3007_2.geometry} material={nodes.Mesh_3007_2.material} />
        <mesh geometry={nodes.Mesh_3007_3.geometry} material={nodes.Mesh_3007_3.material} />
        <mesh geometry={nodes.Mesh_3007_4.geometry} material={nodes.Mesh_3007_4.material} />
        <mesh geometry={nodes.Mesh_3007_5.geometry} material={nodes.Mesh_3007_5.material} />
      </group>
      <group position={[326.3, 4.81, 145.16]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0014_1'].geometry}
          material={nodes['Box001_02_-_Default_0014_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0014_2'].geometry}
          material={nodes['Box001_02_-_Default_0014_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0014_3'].geometry}
          material={nodes['Box001_02_-_Default_0014_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0014_4'].geometry}
          material={nodes['Box001_02_-_Default_0014_4'].material}
        />
      </group>
      <group position={[323.87, 4.81, 148.86]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0015_1'].geometry}
          material={nodes['Box001_02_-_Default_0015_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0015_2'].geometry}
          material={nodes['Box001_02_-_Default_0015_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0015_3'].geometry}
          material={nodes['Box001_02_-_Default_0015_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0015_4'].geometry}
          material={nodes['Box001_02_-_Default_0015_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0007'].geometry}
        material={nodes['Plane004_13_-_Default_0007'].material}
        position={[326.99, 2.86, 148.22]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0007.geometry}
        material={nodes.Plane001_Material002_0007.material}
        position={[328.02, 2.79, 145.78]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[328.22, 3.68, 130.12]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3008_1.geometry} material={nodes.Mesh_3008_1.material} />
        <mesh geometry={nodes.Mesh_3008_2.geometry} material={nodes.Mesh_3008_2.material} />
        <mesh geometry={nodes.Mesh_3008_3.geometry} material={nodes.Mesh_3008_3.material} />
        <mesh geometry={nodes.Mesh_3008_4.geometry} material={nodes.Mesh_3008_4.material} />
        <mesh geometry={nodes.Mesh_3008_5.geometry} material={nodes.Mesh_3008_5.material} />
      </group>
      <group position={[326.3, 4.81, 131.84]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0016_1'].geometry}
          material={nodes['Box001_02_-_Default_0016_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0016_2'].geometry}
          material={nodes['Box001_02_-_Default_0016_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0016_3'].geometry}
          material={nodes['Box001_02_-_Default_0016_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0016_4'].geometry}
          material={nodes['Box001_02_-_Default_0016_4'].material}
        />
      </group>
      <group position={[323.87, 4.81, 135.55]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0017_1'].geometry}
          material={nodes['Box001_02_-_Default_0017_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0017_2'].geometry}
          material={nodes['Box001_02_-_Default_0017_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0017_3'].geometry}
          material={nodes['Box001_02_-_Default_0017_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0017_4'].geometry}
          material={nodes['Box001_02_-_Default_0017_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0008'].geometry}
        material={nodes['Plane004_13_-_Default_0008'].material}
        position={[326.99, 2.86, 134.9]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0008.geometry}
        material={nodes.Plane001_Material002_0008.material}
        position={[328.02, 2.79, 132.46]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[328.22, 3.68, 116.8]} rotation={[-1.57, -0.03, -0.45]} scale={[-4.25, -5.89, -5.89]}>
        <mesh geometry={nodes.Mesh_3009_1.geometry} material={nodes.Mesh_3009_1.material} />
        <mesh geometry={nodes.Mesh_3009_2.geometry} material={nodes.Mesh_3009_2.material} />
        <mesh geometry={nodes.Mesh_3009_3.geometry} material={nodes.Mesh_3009_3.material} />
        <mesh geometry={nodes.Mesh_3009_4.geometry} material={nodes.Mesh_3009_4.material} />
        <mesh geometry={nodes.Mesh_3009_5.geometry} material={nodes.Mesh_3009_5.material} />
      </group>
      <group position={[326.3, 4.81, 118.52]} rotation={[-Math.PI / 2, 0, 0.67]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0018_1'].geometry}
          material={nodes['Box001_02_-_Default_0018_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0018_2'].geometry}
          material={nodes['Box001_02_-_Default_0018_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0018_3'].geometry}
          material={nodes['Box001_02_-_Default_0018_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0018_4'].geometry}
          material={nodes['Box001_02_-_Default_0018_4'].material}
        />
      </group>
      <group position={[323.87, 4.81, 122.23]} rotation={[-Math.PI / 2, 0, 1.32]} scale={0.04}>
        <mesh
          geometry={nodes['Box001_02_-_Default_0019_1'].geometry}
          material={nodes['Box001_02_-_Default_0019_1'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0019_2'].geometry}
          material={nodes['Box001_02_-_Default_0019_2'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0019_3'].geometry}
          material={nodes['Box001_02_-_Default_0019_3'].material}
        />
        <mesh
          geometry={nodes['Box001_02_-_Default_0019_4'].geometry}
          material={nodes['Box001_02_-_Default_0019_4'].material}
        />
      </group>
      <mesh
        geometry={nodes['Plane004_13_-_Default_0009'].geometry}
        material={nodes['Plane004_13_-_Default_0009'].material}
        position={[326.99, 2.86, 121.59]}
        rotation={[-Math.PI / 2, 0, 1.12]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane001_Material002_0009.geometry}
        material={nodes.Plane001_Material002_0009.material}
        position={[328.02, 2.79, 119.15]}
        rotation={[-Math.PI / 2, 0, 1.29]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[-49.88, 19, 41.57]} rotation={[0, Math.PI / 2, 0]} scale={[22, 15, 13]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={nodes.Cube001_1.material} />
        <mesh geometry={nodes.Cube001_2.geometry} material={nodes.Cube001_2.material} />
        <mesh geometry={nodes.Cube001_3.geometry} material={nodes.Cube001_3.material} />
        <mesh geometry={nodes.Cube001_4.geometry} material={nodes.Cube001_4.material} />
        <mesh geometry={nodes.Cube001_5.geometry} material={nodes.Cube001_5.material} />
        <mesh geometry={nodes.Cube001_6.geometry} material={nodes.Cube001_6.material} />
        <mesh geometry={nodes.Cube001_7.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Cube001_8.geometry} material={nodes.Cube001_8.material} />
        <mesh geometry={nodes.Cube001_9.geometry} material={nodes.Cube001_9.material} />
      </group>
      <group position={[-38.46, -1.31, 36.07]} rotation={[0, Math.PI / 2, 0]} scale={[50.55, 3.56, 72.62]}>
        <mesh geometry={nodes.Plane_1.geometry} material={nodes.Plane_1.material} />
        <mesh geometry={nodes.Plane_2.geometry} material={nodes.Plane_2.material} />
      </group>
      <group position={[-52.12, 15.98, -13.44]} rotation={[0, Math.PI / 2, 0]} scale={[19.97, 17.31, 17.31]}>
        <mesh geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} />
        <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
      </group>
      <group position={[-52.12, 15.98, 91.89]} rotation={[0, Math.PI / 2, 0]} scale={[19.97, 17.31, 17.31]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
        <mesh geometry={nodes.Cube002_2.geometry} material={nodes.Cube002_2.material} />
        <mesh geometry={nodes.Cube002_3.geometry} material={nodes.Cube002_3.material} />
      </group>
      <group position={[3.93, 13, 41.57]} rotation={[0, Math.PI / 2, 0]} scale={[-77.13, 14.09, 38.69]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={nodes.Cube003_1.material} />
        <mesh geometry={nodes.Cube003_2.geometry} material={nodes.Cube003_2.material} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials.roof} />
      </group>
      <mesh
        geometry={nodes.watchmann.geometry}
        material={nodes.watchmann.material}
        position={[331.25, 18.89, 455.59]}
        scale={[31.51, 20.43, 35.09]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-59.27, -0.28, -87]}
        scale={[32.38, 57.77, 19.34]}
      />
      <mesh
        geometry={nodes.achole.geometry}
        material={nodes.achole.material}
        position={[-18.08, 45.32, -7.09]}
        scale={[22, 15, 13]}
      />
      <mesh
        geometry={nodes.achole001.geometry}
        material={nodes.achole001.material}
        position={[-10.66, 45.32, -7.09]}
        scale={[22, 15, 13]}
      />
      <mesh
        geometry={nodes.achole002.geometry}
        material={nodes.achole002.material}
        position={[-18.46, 45.32, 9.33]}
        scale={[22, 15, 13]}
      />
      <mesh
        geometry={nodes.achole003.geometry}
        material={nodes.achole003.material}
        position={[-11.05, 45.32, 9.33]}
        scale={[22, 15, 13]}
      />
      <mesh
        geometry={nodes.achole004.geometry}
        material={nodes.achole004.material}
        position={[15.36, 45.32, 9.33]}
        scale={[22, 15, 13]}
      />
      <mesh
        geometry={nodes.achole005.geometry}
        material={nodes.achole005.material}
        position={[22.78, 45.32, 9.33]}
        scale={[22, 15, 13]}
      />
      <mesh
        geometry={nodes.achole006.geometry}
        material={nodes.achole006.material}
        position={[15.87, 45.32, -7.09]}
        scale={[22, 15, 13]}
      />
      <mesh
        geometry={nodes.achole007.geometry}
        material={nodes.achole007.material}
        position={[23.29, 45.32, -7.09]}
        scale={[22, 15, 13]}
      />
      <mesh
        geometry={nodes.Grid.geometry}
        material={nodes.Grid.material}
        position={[-77.58, 2.73, 111.68]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 3.1]}
      />
      <mesh
        geometry={nodes.Grid001.geometry}
        material={nodes.Grid001.material}
        position={[-77.58, 2.73, 126.28]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 3.1]}
      />
      <mesh
        geometry={nodes.Grid002.geometry}
        material={nodes.Grid002.material}
        position={[-77.58, 11.67, 126.28]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 3.47]}
      />
      <mesh
        geometry={nodes.Grid003.geometry}
        material={nodes.Grid003.material}
        position={[-77.58, 11.67, 111.67]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 3.47]}
      />
      <mesh
        geometry={nodes.Grid004.geometry}
        material={nodes.Grid004.material}
        position={[-77.58, 20.36, 111.67]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 3.11]}
      />
      <mesh
        geometry={nodes.Grid005.geometry}
        material={nodes.Grid005.material}
        position={[-77.58, 20.36, 126.3]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 3.11]}
      />
      <mesh
        geometry={nodes.Grid006.geometry}
        material={nodes.Grid006.material}
        position={[-77.58, 28.26, 126.3]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 2.67]}
      />
      <mesh
        geometry={nodes.Grid007.geometry}
        material={nodes.Grid007.material}
        position={[-77.58, 28.26, 111.67]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 2.67]}
      />
      <mesh
        geometry={nodes.Grid008.geometry}
        material={nodes.Grid008.material}
        position={[-77.58, 36.07, 111.67]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 2.77]}
      />
      <mesh
        geometry={nodes.Grid009.geometry}
        material={nodes.Grid009.material}
        position={[-77.58, 36.07, 126.23]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.44, 1.96, 2.77]}
      />
      <group position={[-44.58, 15.92, -19.44]} scale={[12.77, 8.71, 3.86]}>
        <mesh geometry={nodes.Cube015_1.geometry} material={nodes.Cube015_1.material} />
        <mesh geometry={nodes.Cube015_2.geometry} material={nodes.Cube015_2.material} />
      </group>
      <group position={[-48.27, 15.92, -19.44]} scale={[12.77, 8.71, 3.86]}>
        <mesh geometry={nodes.Cube017_1.geometry} material={nodes.Cube017_1.material} />
        <mesh geometry={nodes.Cube017_2.geometry} material={nodes.Cube017_2.material} />
      </group>
      <group position={[-44.58, 21.21, -19.44]} scale={[12.77, 8.71, 3.86]}>
        <mesh geometry={nodes.Cube018_1.geometry} material={nodes.Cube018_1.material} />
        <mesh geometry={nodes.Cube018_2.geometry} material={nodes.Cube018_2.material} />
      </group>
      <group position={[-48.27, 21.21, -19.44]} scale={[12.77, 8.71, 3.86]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={nodes.Cube019_1.material} />
        <mesh geometry={nodes.Cube019_2.geometry} material={nodes.Cube019_2.material} />
      </group>
      <group position={[-67.8, 9.02, -23.24]} scale={[12.77, 8.71, 3.86]}>
        <mesh geometry={nodes.Cube020_1.geometry} material={nodes.Cube020_1.material} />
        <mesh geometry={nodes.Cube020_2.geometry} material={nodes.Cube020_2.material} />
      </group>
      <group position={[-67.82, 10.49, -23.24]} scale={[12.77, 8.71, 3.86]}>
        <mesh geometry={nodes.Cube021_1.geometry} material={nodes.Cube021_1.material} />
        <mesh geometry={nodes.Cube021_2.geometry} material={nodes.Cube021_2.material} />
      </group>
      <group position={[0, 0, -51.53]}>
        <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} />
        <mesh geometry={nodes.Plane003_1.geometry} material={nodes.Plane003_1.material} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials.brown} />
      </group>
      <mesh
        geometry={nodes.Mesh_0.geometry}
        material={nodes.Mesh_0.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0001.geometry}
        material={nodes.Mesh_0001.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0002.geometry}
        material={nodes.Mesh_0002.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0003.geometry}
        material={nodes.Mesh_0003.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0004.geometry}
        material={nodes.Mesh_0004.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0005.geometry}
        material={nodes.Mesh_0005.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0006.geometry}
        material={nodes.Mesh_0006.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0007.geometry}
        material={nodes.Mesh_0007.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0008.geometry}
        material={nodes.Mesh_0008.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Mesh_0009.geometry}
        material={nodes.Mesh_0009.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Plane004_1.geometry} material={nodes.Plane004_1.material} />
        <mesh geometry={nodes.Plane004_2.geometry} material={nodes.Plane004_2.material} />
        <mesh geometry={nodes.Plane004_3.geometry} material={nodes.Plane004_3.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cube_Cube001_1.geometry} material={nodes.Cube_Cube001_1.material} />
        <mesh geometry={nodes.Cube_Cube001_2.geometry} material={nodes.Cube_Cube001_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cube001_Cube002_1.geometry} material={nodes.Cube001_Cube002_1.material} />
        <mesh geometry={nodes.Cube001_Cube002_2.geometry} material={nodes.Cube001_Cube002_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Circle_1.geometry} material={nodes.Circle_1.material} />
        <mesh geometry={nodes.Circle_2.geometry} material={nodes.Circle_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Circle001_1.geometry} material={nodes.Circle001_1.material} />
        <mesh geometry={nodes.Circle001_2.geometry} material={nodes.Circle001_2.material} />
        <mesh geometry={nodes.Circle001_3.geometry} material={nodes.Circle001_3.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.upper_Plane003_1.geometry} material={nodes.upper_Plane003_1.material} />
        <mesh geometry={nodes.upper_Plane003_2.geometry} material={materials['brown.001']} />
        <mesh geometry={nodes.upper_Plane003_3.geometry} material={materials.black} />
        <mesh geometry={nodes.upper_Plane003_4.geometry} material={materials.white} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cube002_Cube003_1.geometry} material={nodes.Cube002_Cube003_1.material} />
        <mesh geometry={nodes.Cube002_Cube003_2.geometry} material={nodes.Cube002_Cube003_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cube003_Cube004_1.geometry} material={nodes.Cube003_Cube004_1.material} />
        <mesh geometry={nodes.Cube003_Cube004_2.geometry} material={materials['yellow.001']} />
        <mesh geometry={nodes.Cube003_Cube004_3.geometry} material={nodes.Cube003_Cube004_3.material} />
        <mesh geometry={nodes.Cube003_Cube004_4.geometry} material={nodes.Cube003_Cube004_4.material} />
      </group>
      <mesh
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Cube005_Cube006.geometry}
        material={materials.metal_white}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Circle055.geometry}
        material={nodes.Circle055.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cylinder001_Cylinder003_1.geometry} material={nodes.Cylinder001_Cylinder003_1.material} />
        <mesh geometry={nodes.Cylinder001_Cylinder003_2.geometry} material={nodes.Cylinder001_Cylinder003_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cylinder002_Cylinder013_1.geometry} material={nodes.Cylinder002_Cylinder013_1.material} />
        <mesh geometry={nodes.Cylinder002_Cylinder013_2.geometry} material={nodes.Cylinder002_Cylinder013_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cylinder003_Cylinder014_1.geometry} material={nodes.Cylinder003_Cylinder014_1.material} />
        <mesh geometry={nodes.Cylinder003_Cylinder014_2.geometry} material={nodes.Cylinder003_Cylinder014_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cylinder004_Cylinder015_1.geometry} material={nodes.Cylinder004_Cylinder015_1.material} />
        <mesh geometry={nodes.Cylinder004_Cylinder015_2.geometry} material={nodes.Cylinder004_Cylinder015_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cylinder005_Cylinder016_1.geometry} material={materials['brown.002']} />
        <mesh geometry={nodes.Cylinder005_Cylinder016_2.geometry} material={nodes.Cylinder005_Cylinder016_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cylinder006_Cylinder017_1.geometry} material={nodes.Cylinder006_Cylinder017_1.material} />
        <mesh geometry={nodes.Cylinder006_Cylinder017_2.geometry} material={nodes.Cylinder006_Cylinder017_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cylinder007_Cylinder018_1.geometry} material={nodes.Cylinder007_Cylinder018_1.material} />
        <mesh geometry={nodes.Cylinder007_Cylinder018_2.geometry} material={nodes.Cylinder007_Cylinder018_2.material} />
      </group>
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.Cylinder008_Cylinder019_1.geometry} material={nodes.Cylinder008_Cylinder019_1.material} />
        <mesh geometry={nodes.Cylinder008_Cylinder019_2.geometry} material={nodes.Cylinder008_Cylinder019_2.material} />
      </group>
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials['Material.002']}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Stairs_Stairs001.geometry}
        material={materials.Stairs_material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.WindowL_1.geometry} material={nodes.WindowL_1.material} />
        <mesh geometry={nodes.WindowL_2.geometry} material={nodes.WindowL_2.material} />
      </group>
      <mesh
        geometry={nodes.Handle.geometry}
        material={nodes.Handle.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <group position={[262.93, 1.89, 12.08]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.81}>
        <mesh geometry={nodes.WindowR_1.geometry} material={nodes.WindowR_1.material} />
        <mesh geometry={nodes.WindowR_2.geometry} material={nodes.WindowR_2.material} />
      </group>
      <mesh
        geometry={nodes.Handle001.geometry}
        material={nodes.Handle001.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Windows_Sill.geometry}
        material={materials.Sill_material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.CTRL_Hole.geometry}
        material={materials.hidden_material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Cube004_Cube005.geometry}
        material={materials.None}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Stairs001_Stairs002.geometry}
        material={nodes.Stairs001_Stairs002.material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported'].geometry}
        material={nodes['m31-5kexported'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported001'].geometry}
        material={nodes['m31-5kexported001'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported002'].geometry}
        material={nodes['m31-5kexported002'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported003'].geometry}
        material={nodes['m31-5kexported003'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported004'].geometry}
        material={nodes['m31-5kexported004'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported005'].geometry}
        material={nodes['m31-5kexported005'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported006'].geometry}
        material={nodes['m31-5kexported006'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported007'].geometry}
        material={nodes['m31-5kexported007'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported008'].geometry}
        material={nodes['m31-5kexported008'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported009'].geometry}
        material={nodes['m31-5kexported009'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported010'].geometry}
        material={nodes['m31-5kexported010'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported011'].geometry}
        material={nodes['m31-5kexported011'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported012'].geometry}
        material={nodes['m31-5kexported012'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported013'].geometry}
        material={nodes['m31-5kexported013'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported014'].geometry}
        material={nodes['m31-5kexported014'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported015'].geometry}
        material={nodes['m31-5kexported015'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported016'].geometry}
        material={nodes['m31-5kexported016'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported017'].geometry}
        material={nodes['m31-5kexported017'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes['m31-5kexported018'].geometry}
        material={nodes['m31-5kexported018'].material}
        position={[262.93, 1.89, 12.08]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[92.54, 0.83, 159.31]}
        rotation={[0, -0.1, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[89.02, 0.83, 200.66]}
        rotation={[0, -0.1, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[112.63, 0.83, 177.57]}
        rotation={[Math.PI, -0.1, Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[233.67, 0.83, -16.37]}
        rotation={[0, -1.56, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[242.79, 0.83, -16.37]}
        rotation={[0, -1.56, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[251.86, 0.83, -16.37]}
        rotation={[0, -1.56, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[234.2, 0.83, 43.24]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[111.41, 0.83, 42.78]}
        rotation={[Math.PI, -0.01, Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[111.41, 0.83, 52.02]}
        rotation={[Math.PI, -0.01, Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[93.37, 0.83, 83.55]}
        rotation={[0, 0.01, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[93.37, 0.83, 92.79]}
        rotation={[0, 0.01, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[245.61, 0.83, 131.91]}
        rotation={[0, 0.01, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[245.61, 0.83, 141.15]}
        rotation={[0, 0.01, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[278.11, 0.83, 170.42]}
        rotation={[-Math.PI, -0.01, -Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[278.11, 0.83, 179.66]}
        rotation={[-Math.PI, -0.01, -Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[366.92, 0.83, 77.33]}
        rotation={[0, 0.01, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[366.92, 0.83, 86.57]}
        rotation={[0, 0.01, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[366.92, 0.83, 251.44]}
        rotation={[0, 0.01, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[366.92, 0.83, 260.68]}
        rotation={[0, 0.01, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[238.38, 0.83, 249.5]}
        rotation={[0, -0.39, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[234.99, 0.83, 258.35]}
        rotation={[0, -0.39, 0]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[266.3, 0.83, 266.98]}
        rotation={[-Math.PI, 0.39, -Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[262.9, 0.83, 275.83]}
        rotation={[-Math.PI, 0.39, -Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[359.72, 0.83, 520.64]}
        rotation={[Math.PI, -0.02, Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[359.72, 0.83, 529.67]}
        rotation={[Math.PI, -0.02, Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[276.22, 0.83, 364.46]}
        rotation={[Math.PI, -0.34, Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[279.09, 0.83, 373.03]}
        rotation={[Math.PI, -0.34, Math.PI]}
        scale={[1, 0.33, 4.28]}
      />
      <mesh
        geometry={nodes._1_tree.geometry}
        material={nodes._1_tree.material}
        position={[340.51, 0.08, -30.46]}
        scale={[5.36, 4.03, 5.36]}
      />
      <mesh
        geometry={nodes._2_tree.geometry}
        material={nodes._2_tree.material}
        position={[351.71, 0.08, -30.46]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._3_tree.geometry}
        material={nodes._3_tree.material}
        position={[364.19, 0.08, -30.46]}
        rotation={[1.23, -0.06, 0.23]}
        scale={[2.16, 2.16, 2.68]}
      />
      <mesh
        geometry={nodes._4_tree.geometry}
        material={materials._4_tree}
        position={[376.39, 0.08, -30.46]}
        rotation={[0.75, -0.05, 1.75]}
        scale={[0.81, 0.5, 1.52]}
      />
      <mesh
        geometry={nodes._5_tree.geometry}
        material={materials._5_tree}
        position={[387.99, -0.04, -30.36]}
        scale={[1.94, 3.36, 1.94]}
      />
      <mesh
        geometry={nodes._6_tree.geometry}
        material={nodes._6_tree.material}
        position={[405.38, -0.04, -30.36]}
        scale={1.42}
      />
      <mesh
        geometry={nodes._7_tree.geometry}
        material={materials._7_tree}
        position={[420.9, 0.08, -30.46]}
        rotation={[-2.77, -0.45, -3.1]}
        scale={[3.1, 4.3, 3.1]}
      />
      <mesh
        geometry={nodes._10_tree.geometry}
        material={materials._10_tree}
        position={[463.32, -0.05, -29.69]}
        rotation={[0, -1.57, 0]}
        scale={0.51}
      />
      <mesh
        geometry={nodes._11_tree.geometry}
        material={materials._11_tree}
        position={[478.09, -0.05, -29.69]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.93}
      />
      <mesh
        geometry={nodes._12_tree.geometry}
        material={materials._12_tree}
        position={[488.92, -0.05, -29.69]}
        rotation={[0, -1.57, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes._8_tree.geometry}
        material={materials._8_tree}
        position={[435.33, -0.05, -29.69]}
        rotation={[0, -1.57, 0]}
        scale={0.64}
      />
      <mesh
        geometry={nodes._9_tree.geometry}
        material={materials._9_tree}
        position={[447.7, -0.03, -29.69]}
        rotation={[0, -1.57, 0]}
        scale={0.35}
      />
      <mesh
        geometry={nodes.Rock_1_.geometry}
        material={materials.Rock_1_}
        position={[511.6, -0.37, -25.61]}
        rotation={[Math.PI, -1.29, Math.PI]}
        scale={[3, 4.62, 3]}
      />
      <mesh
        geometry={nodes._2_tree001.geometry}
        material={nodes._2_tree001.material}
        position={[238.94, -0.95, 48.29]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._2_tree002.geometry}
        material={nodes._2_tree002.material}
        position={[230.18, -0.95, 48.29]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._2_tree003.geometry}
        material={nodes._2_tree003.material}
        position={[222.11, -0.95, -1.22]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._2_tree004.geometry}
        material={nodes._2_tree004.material}
        position={[228.6, -0.95, -20.81]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._2_tree005.geometry}
        material={nodes._2_tree005.material}
        position={[277.13, -0.95, -20.81]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._3_tree001.geometry}
        material={nodes._3_tree001.material}
        position={[252.61, -0.93, -21.47]}
        rotation={[1.26, 0.17, -0.45]}
        scale={[4.19, 4.19, 5.21]}
      />
      <mesh
        geometry={nodes._3_tree002.geometry}
        material={nodes._3_tree002.material}
        position={[117.4, -0.93, 44.08]}
        rotation={[1.22, 0.02, -0.01]}
        scale={[4.19, 4.19, 5.21]}
      />
      <mesh
        geometry={nodes._3_tree003.geometry}
        material={nodes._3_tree003.material}
        position={[118.28, -0.93, 175.17]}
        rotation={[1.22, 0.02, -0.01]}
        scale={[4.19, 4.19, 5.21]}
      />
      <mesh
        geometry={nodes._3_tree004.geometry}
        material={nodes._3_tree004.material}
        position={[82.43, -0.93, 202.5]}
        rotation={[1.89, 0.14, -2.68]}
        scale={[4.19, 4.19, 5.21]}
      />
      <mesh
        geometry={nodes._6_tree001.geometry}
        material={nodes._6_tree001.material}
        position={[356.89, -1.68, 77.51]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._6_tree002.geometry}
        material={nodes._6_tree002.material}
        position={[80.79, -2.29, -42.56]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._2_tree006.geometry}
        material={nodes._2_tree006.material}
        position={[48.68, -1.73, -46.11]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._2_tree007.geometry}
        material={nodes._2_tree007.material}
        position={[-85.47, -1.73, -45.88]}
        scale={2.39}
      />
      <mesh
        geometry={nodes._3_tree005.geometry}
        material={nodes._3_tree005.material}
        position={[127.88, -1.62, -30.11]}
        rotation={[1.23, -0.06, 0.23]}
        scale={[5.69, 5.69, 7.08]}
      />
      <mesh
        geometry={nodes._1_tree001.geometry}
        material={nodes._1_tree001.material}
        position={[-26.9, -2.31, -43.69]}
        scale={[5.36, 4.03, 5.36]}
      />
      <mesh
        geometry={nodes._3_tree006.geometry}
        material={nodes._3_tree006.material}
        position={[-65.62, -1.62, -42.61]}
        rotation={[1.82, 0.25, -2.33]}
        scale={[4.59, 4.59, 5.72]}
      />
      <mesh
        geometry={nodes.pCube265.geometry}
        material={materials.blinn1}
        position={[-57.25, 8.48, -84.59]}
        rotation={[0.29, 0, 0]}
        scale={[0.02, 0.02, 0.02]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-7.31, 0, -318.15]}
        scale={199.58}
      />
    </group>
  )
}

useGLTF.preload('/compressed_clg.glb')
