const eventDetails = [
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "War Of Branches",
  //   Fee: [{ Fee: "60", Type: "Solo" }],
  //   Category: "Cultural",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "Abhinaya",
  //   Fee: [{ Fee: "60", Type: "Solo" }],
  //   Category: "Cultural",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "Carnival",
  //   Fee: [{ Fee: "60", Type: "Solo" }],
  //   Category: "Cultural",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "Open Mic",
  //   Fee: [{ Fee: "60", Type: "Solo" }],
  //   Category: "Cultural",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "Short Circuit",
  //   Fee: [{ Fee: "60", Type: "Team(2)" }],
  //   Category: "Technical",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "E-Sports",
  //   Fee: [{ Fee: "60", Type: "Team(2)" }],
  //   Category: "Fun",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "Paintball",
  //   Fee: [{ Fee: "60", Type: "Team(2)" }],
  //   Category: "Fun",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "Footpool",
  //   Fee: [{ Fee: "60", Type: "Team(2)" }],
  //   Category: "Fun",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "Human Foosball",
  //   Fee: [{ Fee: "60", Type: "Team(2)" }],
  //   Category: "Fun",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "SPIT-Hackathon",
  //   Fee: [{ Fee: "60", Type: "Team(2)" }],
  //   Category: "Pre-Events",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
  {
    Data: "14 Mar",
    Description: "",
    Title: "Advert Einstein",
    Fee: [{ Fee: "60", Type: "Team(2)" }],
    Category: "Pre-Events",
    Prizes: "Rs. 10000",
    rules: [],
    faq: [],
    isSingle: false,
    max: 2,
  },
  // {
  //   Data: "14 Mar",
  //   Description: "",
  //   Title: "Tech Race",
  //   Fee: [{ Fee: "60", Type: "Team(2)" }],
  //   Category: "Pre-Events",
  //   Prizes: "Rs. 10000",
  //   rules: [],
  //   faq: [],
  //   isSingle: false,
  //   max: 2,
  // },
];

export { eventDetails };
